const moduleMappingSideNav = require('../../../test-data/sidemenuMap.js');

module.exports =  {
        highlightModuleSelector:`(//aside[@id="main-side-nav-aside"]//a[${moduleMappingSideNav.highlights}])[1]`,
        tenureModuleSelector :`//aside[@id="main-side-nav-aside"]//a[${moduleMappingSideNav.tenure}]`,
        sideMenu : "//div[@class = 'side-menu-scrollable-section']",
        sideMenuLogo : "//div[@class='side-nav-top']/figure",
        ptmCasesIdentified : "(//div[@class='ds-sc-score'])[2]//p",
        ptmCasesClosed : "(//div[@class='ds-sc-score'])[3]//p",
        tenureHighlightsTab :"//h6[text()='Tenure Highlights']",
        engagmentScoresHighlights : "(//div[@class='score-card']//div[contains(@class,'ds-sc-formatted-score')]//p)[1]",
        npsHighlights : "(//div[@class='score-card']//div[contains(@class,'ds-sc-formatted-score')]//p)[2]",
        moodScoreHighlights : "(//div[@class='score-card']//div[contains(@class,'ds-sc-formatted-score')]//p)[3]",
        responseRateHighlights: "(//div[@class='score-card']//div[contains(@class,'ds-sc-formatted-score')]//p)[4]",
        totalPTMHighlights : "(//div[@class='score-card']//div[contains(@class,'ds-sc-formatted-score')]//p)[5]",
        engagmentScoresTenure :"(//div[@class='ds-score-card ']//div[contains(@class,'ds-sc-formatted-score')]//p)[1]",
        npsTenure : "(//div[@class='ds-score-card ']//div[contains(@class,'ds-sc-formatted-score')]//p)[2]",
        moodScoreTenure : "(//div[@class='ds-score-card ']//div[contains(@class,'ds-sc-formatted-score')]//p)[3]",
        responseRateTenure : "(//div[@class='ds-score-card ']//div[contains(@class,'ds-sc-formatted-score')]//p)[4]",
        totalPTMTenure : "//div[@class='ptm-heading-flex']/p",
        dateFilter : "//div[@class='column columns no-padding is-justify-content-flex-start dropdown-filters']//div//div[@id='custom-date-dropdown-div-id']",
        dateFilterTenure : "//div[@class='column columns no-padding is-justify-content-flex-start dropdown-filters']//div//span[@class='font-13 has-text-grey padding-right-5']",
        cancelDateFilter : "//span[text()='Cancel']",
        applyDateFilter : "//span[text()='Apply']",
        dateFilter2 : "((//div[@id='custom-date-dropdown-div-id'])[1]//span)[2]",
        startDate : "(//div[@class='rdrDateDisplayWrapper']//input)[1]",
        endDate : "(//div[@class='rdrDateDisplayWrapper']//input)[2]",
        engagmentAnalyticsTab : "//h6[text()='Engagement Analytics']",
        overallHeading : "//h3[text()='Overall']",
        ptmCasesIdentifiedHeading : "//h5[text()='New PTM cases identified']",
        ESText : "(//div[@class='ds-sc-delta']/p)[1]",
        NPSText : "(//div[@class='ds-sc-delta']/p)[2]",
        MSText : "(//div[@class='ds-sc-delta']/p)[3]",
        RRText :  "(//div[@class='ds-sc-delta']/p)[4]",
        lestThan1Year : "//h5[text()='<1 year']",
        seeMoreES : "(//div[@class='ds-sc-footer has-justify-content-center']//span)[1]",
        backArrow : "//section[@class='align-items-center flex-1']/button",
        oneToThreeYear : "//h5[text()='1-3 years']",
        threeToFiveYear :"//h5[text()='3-5 years']",
        fiveToTenYear :"//h5[text()='5-10 years']",
        MoreThanTenYear : "//h5[text()='>10years']"

}